# Generated by Django 4.0.2 on 2022-06-14 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='design_total',
        ),
    ]
