# Generated by Django 4.0.2 on 2022-06-12 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='profile',
        ),
        migrations.AddField(
            model_name='review',
            name='comment_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
