# Generated by Django 4.0.2 on 2022-06-14 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0002_remove_review_design_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='project',
        ),
    ]
