# Generated by Django 4.0.2 on 2022-06-15 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0005_review_avg_design'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='field_name',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
