# Generated by Django 4.0.2 on 2022-06-09 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0006_alter_review_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rate',
            field=models.CharField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5)], max_length=300),
        ),
    ]
