# Generated by Django 4.0.2 on 2022-06-15 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0006_review_field_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='field_name',
            new_name='date',
        ),
    ]
