# Generated by Django 4.0.2 on 2022-06-15 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0010_projects_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='avg_design',
        ),
    ]
