# Generated by Django 4.0.2 on 2022-06-15 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0012_remove_projects_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='project_images'),
        ),
    ]
