# Generated by Django 4.0.2 on 2022-06-10 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0013_alter_review_content_rate_alter_review_use_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='content_rate',
            field=models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='design_rate',
            field=models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='use_rate',
            field=models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], max_length=300, null=True),
        ),
    ]
