# Generated by Django 4.0.2 on 2022-06-10 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0018_alter_review_content_rate_alter_review_design_rate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='content_rate',
            new_name='content_rating',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='design_rate',
            new_name='design_rating',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='use_rate',
            new_name='user_experience_rating',
        ),
    ]
