# Generated by Django 4.0.2 on 2022-06-11 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0021_remove_review_profile_projects_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='profile',
        ),
        migrations.AddField(
            model_name='review',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='awards.profile'),
        ),
    ]
