# Generated by Django 4.0.2 on 2022-07-01 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0021_alter_text_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='text',
            field=models.TextField(max_length=300),
        ),
    ]
